language: node_js
node_js:
  - "0.10"

script:
  - make test-cov
  - make test-front
  - cat coverage/karma/*/lcov.info coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js > /dev/null 2>&1

services:
  - redis-server