language: node_js
node_js:
  - 6
  - 8
  - node
sudo: false
script:
  - make test-cov
  - make test-front
after_script:
  - cat coverage/karma/*/lcov.info coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js > /dev/null 2>&1
